### ISSUE TITLE
enhanced and corrected buttonmap.xml

### ISSUE THREAD

**Issue by ajbathe** [kodi-game/game.libretro.dosbox#13] opened 2023-04-14 20:57 UTC
[buttonmap.xml.txt](https://github.com/kodi-game/game.libretro.dosbox/files/11237067/buttonmap.xml.txt)

```patch
diff --git a/game.libretro.dosbox/resources/buttonmap.xml b/game.libretro.dosbox/resources/buttonmap.xml
index 6ac4121..a03d478 100644
--- a/game.libretro.dosbox/resources/buttonmap.xml
+++ b/game.libretro.dosbox/resources/buttonmap.xml
@@ -101,7 +101,7 @@
     <feature name="period" mapto="RETROK_PERIOD"/>
     <feature name="comma" mapto="RETROK_COMMA"/>
     <feature name="slash" mapto="RETROK_SLASH"/>
-    <feature name="printscreen" mapto="RETROK_SYSREQ"/>
+    <feature name="printscreen" mapto="RETROK_PRINT"/>
     <feature name="pause" mapto="RETROK_PAUSE"/>
     <feature name="insert" mapto="RETROK_INSERT"/>
     <feature name="home" mapto="RETROK_HOME"/>
@@ -127,8 +127,46 @@
     <feature name="kpmultiply" mapto="RETROK_KP_MULTIPLY"/>
     <feature name="kpminus" mapto="RETROK_KP_MINUS"/>
     <feature name="kpplus" mapto="RETROK_KP_PLUS"/>
-    <feature name="kpenter" mapto="RETROK_KP_PLUS"/>
+    <feature name="kpenter" mapto="RETROK_KP_ENTER"/>
     <feature name="kpperiod" mapto="RETROK_KP_PERIOD"/>
     <feature name="grave" mapto="RETROK_BACKQUOTE"/>
+    <feature name="f13" mapto="RETROK_F13"/>
+    <feature name="f14" mapto="RETROK_F14"/>
+    <feature name="f15" mapto="RETROK_F15"/>
+    <feature name="leftmeta" mapto="RETROK_LMETA"/>
+    <feature name="rightmeta" mapto="RETROK_RMETA"/>
+    <feature name="leftsuper" mapto="RETROK_LSUPER"/>
+    <feature name="rightsuper" mapto="RETROK_RSUPER"/>
+    <feature name="exclaim" mapto="RETROK_EXCLAIM"/>
+    <feature name="doublequote" mapto="RETROK_QUOTEDBL"/>
+    <feature name="hash" mapto="RETROK_HASH"/>
+    <feature name="ampersand" mapto="RETROK_AMPERSAND"/>
+    <feature name="leftparen" mapto="RETROK_LEFTPAREN"/>
+    <feature name="rightparen" mapto="RETROK_RIGHTPAREN"/>
+    <feature name="asterisk" mapto="RETROK_ASTERISK"/>
+    <feature name="plus" mapto="RETROK_PLUS"/>
+    <feature name="colon" mapto="RETROK_COLON"/>
+    <feature name="less" mapto="RETROK_LESS"/>
+    <feature name="greater" mapto="RETROK_GREATER"/>
+    <feature name="question" mapto="RETROK_QUESTION"/>
+    <feature name="at" mapto="RETROK_AT"/>
+    <feature name="caret" mapto="RETROK_CARET"/>
+    <feature name="underscore" mapto="RETROK_UNDERSCORE"/>
+    <feature name="dollar" mapto="RETROK_DOLLAR"/>
+    <feature name="leftbrace" mapto="RETROK_LEFTBRACE"/>
+    <feature name="rightbrace" mapto="RETROK_RIGHTBRACE"/>
+    <feature name="bar" mapto="RETROK_BAR"/>
+    <feature name="tilde" mapto="RETROK_TILDE"/>
+    <feature name="mode" mapto="RETROK_MODE"/>
+    <feature name="compose" mapto="RETROK_COMPOSE"/>
+    <feature name="help" mapto="RETROK_HELP"/>
+    <feature name="sysreq" mapto="RETROK_SYSREQ"/>
+    <feature name="break" mapto="RETROK_BREAK"/>
+    <feature name="menu" mapto="RETROK_MENU"/>
+    <feature name="power" mapto="RETROK_POWER"/>
+    <feature name="euro" mapto="RETROK_EURO"/>
+    <feature name="undo" mapto="RETROK_UNDO"/>
+    <feature name="kpequals" mapto="RETROK_KP_EQUALS"/>
+    <feature name="clear" mapto="RETROK_CLEAR"/>
   </controller>
 </buttonmap>
```

**Comment by garbear** [comment] 2023-04-15 17:24
@ajbathe Thanks for donating buttonmap corrections! I updated the description to show the patch.

Some comments:

The `<feature name="kpenter" mapto="RETROK_KP_ENTER"/>` change looks correct.

The `<feature name="printscreen" mapto="RETROK_PRINT"/>` *should be* correct but conflicts with `RETROK_SYSREQ` in the source of [dosbox](https://github.com/libretro/dosbox-libretro/blob/master/libretro/mapper.cpp#L56) / [dosbox-core](https://github.com/libretro/dosbox-core/blob/libretro/libretro/src/libretro_dosbox.h#L114) / [dosbox-pure](https://github.com/libretro/dosbox-pure/blob/main/dosbox_pure_libretro.cpp#L3967) / [dosbox-svn](https://github.com/libretro/dosbox-svn/blob/libretro/libretro/libretro_mapper.cpp#L61).

I think the dosbox sources are incorrect. I checked the [RetroArch source](https://github.com/libretro/RetroArch/blob/master/input/input_keymaps.c#L766-L771) and I think the key should be `RETROK_PRINT`, making the change here correct and requiring a patch in all dosbox cores.

However, the keys added at the end don't appear in the sources linked above, so they won't have any effect, right? Have you tested any of these keys?

**Comment by ajbathe** [comment] 2023-04-17 08:51
I did some research because some keys within libretro emulators didn't function correctly, so I extracted the labels out of .kodi/addons/game.libretro/game.libretro.so.20.2.3 and compared them with the used buttonmap.xml - so I discovered some false und missing entries

my suggestion of the extended and corrected buttonmaps is fully consistent with https://github.com/kodi-game/game.libretro/blob/Omega/src/input/DefaultKeyboardTranslator.cpp

my final thought: it won't be only used by dosbox but other emulators too

**Comment by ajbathe** [comment] 2023-04-17 08:55
RETROK_SYSREQ was used twice: feature names printscreen and sysreq are mapped to RETROK_SYSREQ

**Comment by garbear** [comment] 2023-04-18 03:34
> I discovered some false und missing entries

The false entries you discovered will be fixed, but the missing entries are on purpose.

[DefaultKeyboardTranslator.cpp](https://github.com/kodi-game/game.libretro/blob/Omega/src/input/DefaultKeyboardTranslator.cpp) is used if keyboard entries are missing from buttonmap.xml.

However, buttonmap.xml has keyboard entries, so they "override" DefaultKeyboardTranslator.cpp. In this case, everything is the same but some entries are missing. The missing entries indicate to Kodi that dosbox doesn't use them, as you can see that they are missing in the dosbox sources.

> RETROK_SYSREQ was used twice

Where do you see this?

Regarding RETROK_SYSREQ, we need to find out what RetroArch does. Can you confirm that print screen is broken in dosbox when using RetroArch? If so, we'll use your correction, if not, we should leave it as RETROK_SYSREQ.

**Comment by ajbathe** [comment] 2023-04-18 15:27
I am struggling to bring the emulators DOSbox and Caprice32 to work. In both emulators I am not able to see many keys like exclaim and dollar, e.g.

**Comment by garbear** [comment] 2023-04-19 20:12
Dropped input is usually straightforward to fix. You need the complete chain: From Kodi input, to controller profile, to libretro API, to core. If any are missing the input will be dropped. You should verify the keys are defined in all four places, and if input is still being dropped, you can upload a debug log (both mapping in the controller GUI and pressing the key during gameplay) and I'll see what the problem is.

**Comment by garbear** [comment] 2023-04-19 20:15
> RETROK_SYSREQ was used twice: feature names printscreen and sysreq are mapped to RETROK_SYSREQ

I don't see where this is. Can you link?

**Comment by garbear** [comment] 2023-04-20 04:29
I've opened PRs for the KP_ENTER fix:

* https://github.com/kodi-game/game.libretro.dosbox/pull/14
* https://github.com/kodi-game/game.libretro.dosbox-core/pull/1
* https://github.com/kodi-game/game.libretro.dosbox-pure/pull/1

It doesn't include the printscreen fix. This entry isn't for which key on the keyboard is being pressed, it's for which constant is expected by the core. As you can see in the sources, cores expect `RETROK_SYSREQ`. Therefore we "describe" the cores as expecting RETROK_SYSREQ in buttonmap.xml, even though it's hooked up to the printscreen button.

It also doesn't include the "missing" keys. These don't appear in the dosbox sources, as you can see.

buttonmap.xml is a description of the core, and it appropriately describes the core as not understanding any of these keys.

**Comment by garbear** [comment] 2023-04-21 10:45
@ajbathe What does don't work for you with the KP_ENTER fix applied? Otherwise are the PRs good to go?

**Comment by garbear** [comment] 2023-07-13 00:15
I've merged the three PRs. @ajbathe let me know if you come across any more issues!

**Comment by garbear** [comment] 2024-08-03 23:14
Closing as completed - if there's still issues with dosbox cores and keymaps reopen this issue or create a new one!

**Closed as completed by garbear** 2024-08-03 23:14 UTC
